### ISSUE TITLE
Cancel button always on left

### ISSUE THREAD

**Issue by nitrag** [lightningkite/LKAlertController#39]
I can't get the Cancel button to be on the right. I tried switching the order of `addAction` and I also played around with `addAction(String)` vs `addAction(String, style, handler)`.

```
       Alert(title: "Add", message: "test")
                .addTextField(&nameField)
                .addTextField(&descriptionField)
                .addAction("Save", style: .default, handler: { _ in
                    print(nameField.text!)
                    print("Description: ", descriptionField.text!)
                })
                .addAction("Cancel")
                .show()
```

_From Human Interface Guideline:
In a two-button alert that proposes a potentially risky action, the button that cancels the action should be on the right (and light-colored).
In a two-button alert that proposes a benign action that people are likely to want, the button that cancels the action should be on the left (and dark-colored)._

**Comment by eriksargent** [comment]
Interesting, I had never noticed that UIAlertController arranged the order of the buttons. It looks like it handles it automatically based on the styles of the buttons, however, I'm not sure it's handled correctly. 

I believe it works for the second case with a benign action, and a cancel button. If I do:

```
.addAction("First", style: .cancel, handler: nil).addAction("Second", style: .default, handler: nil)
```

The `First` button is on the left (as it should be) and is bolded to match the cancel style, and the `Second` is lighter and on the right.
![screen shot 2016-11-14 at 3 22 20 pm](https://cloud.githubusercontent.com/assets/10200525/20285272/27764dfe-aa7e-11e6-9328-c509f7ddf57a.png)

If I swap the styles of the actions, the `Second` button is moved to the left side and made dark (once again, as it should be).

```
.addAction("First", style: .default, handler: nil).addAction("Second", style: .cancel, handler: nil)
```

![screen shot 2016-11-14 at 3 23 50 pm](https://cloud.githubusercontent.com/assets/10200525/20285309/5cc12290-aa7e-11e6-8679-422a2800c8b5.png)

So the second case seems to work. However, if I mark one item as `destructive` and the other as `cancel`, the order is backwards (according to the first case). It appears that the button marked cancel is always dark and always on the left. However, according the the line from the HIG that you referenced, the cancel button should be lighter and on the right instead.

```
.addAction("First", style: .destructive, handler: nil).addAction("Second", style: .cancel, handler: nil)
```

![screen shot 2016-11-14 at 3 26 25 pm](https://cloud.githubusercontent.com/assets/10200525/20285369/b91a79c4-aa7e-11e6-874d-63b4caf5a6c4.png)

It appears that for this case you need to use the `default` style instead of `cancel`.

```
.addAction("First", style: .destructive, handler: nil).addAction("Second", style: .default, handler: nil)
```

![screen shot 2016-11-14 at 3 32 52 pm](https://cloud.githubusercontent.com/assets/10200525/20285523/a013e8b0-aa7f-11e6-81b6-2658aeda8a08.png)

So, this does work, but it's not immediately clear from the way iOS sets this up. To make it work for your destructive button, style the other button as `default`rather than `cancel`.

What part of the HIG does this come from? Will you post the link?

**Comment by nitrag** [comment]
I can't find the HIG link, but I see several posts about it. Regardless...

Why is it that `.cancel` style always bolded when I actually want the `.default` button to be bolded? If applying `.cancel` style does nothing other than making it bold text and forcing first, we should rename it to `.primary` because "cancel" is misleading. 

See, this is counter-intuitive:

```
Alert(title: "Add Waypoint", message: String(format: "%.6f, %.6f", coord.latitude, coord.longitude))
.addTextField(&nameField)
.addTextField(&descriptionField)
.addAction("Save", style: .cancel, handler: { _ in //this is bold and first
    //do stuff
})
.addAction("Cancel", style: .default, handler: nil) //this is not bold and second, also, it must be .default else error for having 2 "cancels"
.show()
```

**Comment by nitrag** [comment]
Well, I did find `preferredAction` but `style: .cancel` will override that.

Having to do this to produce desired result:

```
Alert(title: "Add Waypoint", message: "message")
.addTextField(&nameField)
.addAction("Save", style: .default, preferredAction: true, handler: { _ in //this is bold and first
    //do stuff
})
.addAction("Cancel", style: .default, handler: nil) //this is not bold and second
.show()
```

**Comment by eriksargent** [comment]
I'm honestly not sure why I made the default `cancel`. I will change that to `default`

I use the same styles that the system uses to avoid confusion and let the system handle everything. 

I did find information about the alert in the HIG: https://developer.apple.com/ios/human-interface-guidelines/ui-views/alerts/

It is being handled the way that it should be. I'm not sure where the line you're quoting came from (I'm guessing it's from an older version), but from the most recent guidelines, the cancel button should always be on the left.

**Comment by nitrag** [comment]
Sorry I'm new to iOS and must have just trusted the first thing I googled. Sorry for the confusion. No changes needed, the following works per HIG specs.

```
let alert = Alert(title: title, message: message).addTextField(&nameField)
if(description){
    alert.addTextField(&descriptionField)
}
alert.addAction("Save", style: .default, preferredAction: true, handler: { _ in

})
.addAction("Cancel", style: .cancel, handler: nil)
.show()
```

Thanks for the help!
